# Generated by Django 4.0.4 on 2022-05-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Пожарная часть')),
                ('number_fighters', models.IntegerField(default=1, verbose_name='Кол-во бойцов')),
                ('address_location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес ПЧ')),
                ('year_of_construction', models.IntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('year_of_renewal', models.IntegerField(blank=True, null=True, verbose_name='Дата капитального ремонта')),
            ],
            options={
                'verbose_name': 'Пожарная часть',
                'verbose_name_plural': 'Пожарные части',
            },
        ),
    ]
