# Generated by Django 3.1.7 on 2022-07-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('department_structure', '0003_auto_20220711_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firedepartment',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='city.city'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
