version: "3.3"

services:

  redis:
    image: redis
    volumes:
      - ./:/redis
    ports:
      - "6379:6379"
    restart: always

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    entrypoint:
      - ./entrypoint.sh
    depends_on:
      - redis
    ports:
      - "80:8000"
    restart: always

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - "81:81"
      - "443:443"
    volumes:
      - ./docker/nginx/certs:/etc/ssl/certs
      - ./application/static:/static
    restart: always

  postgres:
    image: postgres:latest
    volumes:
      - ./postgres_backups:/var/postgres_backups
    environment:
      POSTGRES_DB: "call_center"
      POSTGRES_USER: "call_center_admin"
      POSTGRES_PASSWORD: "bw4QSm9bMH9qfxXe"
    ports:
      - "5432:5432"
