# Generated by Django 4.0.4 on 2022-05-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Должность')),
                ('main_position', models.BooleanField(default=False, verbose_name='Должности которые только из ЦОУСС менять можно')),
                ('fire_fighter', models.BooleanField(default=True, verbose_name='Те кто выезжает на пожар, боевые')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, null=True, unique=True, verbose_name='Примечание ЛС')),
            ],
            options={
                'verbose_name': 'Примечание',
                'verbose_name_plural': 'Примечания личного состава',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=12, unique=True, verbose_name='ИИН')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ф.И.О.')),
                ('gdzs', models.BooleanField(default=True, verbose_name='ГДЗС')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department_structure.firedepartment', verbose_name='ПЧ')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.position', verbose_name='Должность')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.status', verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
