# Generated by Django 4.0.4 on 2022-05-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Караул',
                'verbose_name_plural': 'Караулы',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='sentry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='personnel.sentry', verbose_name='караул'),
            preserve_default=False,
        ),
    ]
