# Generated by Django 3.1.7 on 2022-11-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_auto_20220711_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='karaul',
            field=models.CharField(default='1-караул', max_length=30, verbose_name='Караул'),
        ),
    ]
