# Generated by Django 3.1.7 on 2022-11-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_position_karaul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='karaul',
        ),
        migrations.AddField(
            model_name='staff',
            name='karaul',
            field=models.CharField(default='1-караул', max_length=30, verbose_name='Караул'),
        ),
    ]
