# Generated by Django 3.1.7 on 2022-11-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_auto_20221130_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='karaul',
        ),
    ]
