# Generated by Django 3.1.7 on 2022-07-10 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=20, unique=True)),
                ('number_in', models.CharField(max_length=20, verbose_name='Номер тел. клиента')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('first_api', models.BooleanField(default=False)),
                ('second_api', models.BooleanField(default=False)),
                ('downloaded', models.BooleanField(default=False)),
                ('mark_quality', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorderPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(blank=True, max_length=4000)),
                ('section', models.CharField(blank=True, max_length=150)),
                ('reference_answer', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория вопроса',
                'verbose_name_plural': 'Категория вопросов',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sip_number', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('operator', models.BooleanField(blank=True, default=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователя ПО',
                'verbose_name_plural': 'Пользователи ПО',
            },
        ),
        migrations.CreateModel(
            name='StatisticQuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('call_number', models.IntegerField(default=0, verbose_name='Кол-во принятых звонков')),
                ('question_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.questioncategory', verbose_name='Категория вопроса')),
            ],
            options={
                'verbose_name': 'Кол-во по категории вопросов',
                'verbose_name_plural': 'Кол-во по категории вопросов',
            },
        ),
        migrations.CreateModel(
            name='StatisticCallNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('call_number', models.IntegerField(default=0, verbose_name='Кол-во принятых звонков')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.userinfo', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Кол-во принятых звонков',
                'verbose_name_plural': 'Кол-во принятых звонков',
            },
        ),
        migrations.CreateModel(
            name='CurrentAppeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_call_start', models.DateTimeField(blank=True, null=True, verbose_name='Время начала звонка')),
                ('date_of_call_end', models.DateTimeField(blank=True, null=True, verbose_name='Время конца звонка')),
                ('income_call_number', models.BigIntegerField(blank=True, null=True, verbose_name='Номер тел. клиента')),
                ('callback_number', models.BigIntegerField(blank=True, null=True, verbose_name='Номер для обратной связи')),
                ('income_call_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО заявителя')),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True, verbose_name='Гражданство')),
                ('iin', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИИН заявителя')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=5, null=True, verbose_name='Дом')),
                ('flat', models.CharField(blank=True, max_length=3, null=True, verbose_name='Кв')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('short_question', models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткая фабула вопроса обращения')),
                ('answer_to_short_question', models.TextField(blank=True, max_length=500, null=True, verbose_name='Ответ на вопрос обращения')),
                ('responsible_department', models.CharField(choices=[('c', 'CALL ЦЕНТР'), ('d', 'ПОГРАНИЧНАЯ СЛУЖБА')], default='c', max_length=1)),
                ('responsible_department_person', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Рассмотрен')),
                ('api_unique_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.apidata')),
                ('borderpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.borderpost')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.city')),
                ('question_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.questioncategory', verbose_name='Категория вопроса')),
                ('user_created_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.userinfo', verbose_name='Пользователь кто создал путевку')),
            ],
            options={
                'verbose_name': 'Текущее обращение',
                'verbose_name_plural': 'Текущие обращения',
            },
        ),
        migrations.AddField(
            model_name='apidata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.userinfo'),
        ),
    ]
