# Generated by Django 3.1.7 on 2022-07-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department_structure', '0003_auto_20220711_2129'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.city'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department_structure.firedepartment', verbose_name='Пожарная часть (если не оператор)'),
        ),
    ]
