# Generated by Django 3.1.7 on 2022-07-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_structure', '0003_auto_20220711_2129'),
        ('application', '0002_auto_20220711_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentappeal',
            name='department',
            field=models.ManyToManyField(to='department_structure.FireDepartment', verbose_name='Пожарная часть'),
        ),
    ]
