# Generated by Django 3.1.7 on 2022-07-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20220711_2129'),
        ('application', '0003_currentappeal_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentappeal',
            name='transport',
            field=models.ManyToManyField(blank=True, to='transport.Transport', verbose_name='Привлеченные силы и средства'),
        ),
    ]
