# Generated by Django 3.1.7 on 2022-07-13 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_currentappeal_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Cобытие')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Список частых событий (для журнала событий)',
            },
        ),
        migrations.CreateModel(
            name='JournalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=500, null=True, verbose_name='Событие')),
                ('date_insert', models.DateTimeField(verbose_name='Время')),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.currentappeal', verbose_name='Выезд - Текущие')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Журнал событий',
            },
        ),
    ]
