# Generated by Django 3.1.7 on 2022-07-13 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_currentappeal_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Ранг',
                'verbose_name_plural': 'Ранги',
            },
        ),
        migrations.CreateModel(
            name='EmergencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.AddField(
            model_name='currentappeal',
            name='object_owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Владелец объекта'),
        ),
        migrations.AddField(
            model_name='currentappeal',
            name='emergency_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.emergencyrank', verbose_name='Ранг выезда'),
        ),
        migrations.AddField(
            model_name='currentappeal',
            name='emergency_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.emergencytype', verbose_name='Тип выезда'),
        ),
    ]
