# Generated by Django 3.1.7 on 2022-07-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('application', '0007_auto_20220713_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentappeal',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='city.city'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='city.city'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
