# Generated by Django 3.1.7 on 2022-07-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20220713_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentappeal',
            name='emergency_closed',
            field=models.BooleanField(default=False, verbose_name='Вызов закрыть'),
        ),
    ]
