# Generated by Django 3.1.7 on 2022-07-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_currentappeal_emergency_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория объекта',
                'verbose_name_plural': 'Категории объекта',
            },
        ),
    ]
