# Generated by Django 3.1.7 on 2022-07-13 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_objectcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentappeal',
            name='object_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.objectcategory', verbose_name='Тип объекта'),
        ),
    ]
