# Generated by Django 3.1.7 on 2022-07-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_currentappeal_object_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentappeal',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
