# Generated by Django 3.1.7 on 2022-07-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20220713_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentappeal',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Рассмотрен'),
        ),
    ]
