# Generated by Django 3.1.7 on 2022-11-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20220714_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentappeal',
            name='callback_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер для обратной связи'),
        ),
        migrations.AlterField(
            model_name='currentappeal',
            name='income_call_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер тел. клиента'),
        ),
    ]
