# Generated by Django 3.1.7 on 2022-12-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20221123_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentappeal',
            name='callback_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Номер для обратной связи'),
        ),
        migrations.AlterField(
            model_name='currentappeal',
            name='income_call_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Номер тел. клиента'),
        ),
    ]
