# Generated by Django 3.1.7 on 2023-01-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20221206_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentappeal',
            name='callback_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер для обратной связи'),
        ),
        migrations.AlterField(
            model_name='currentappeal',
            name='income_call_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер тел. клиента'),
        ),
    ]
