# Generated by Django 3.1.7 on 2023-02-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0002_auto_20220711_2129'),
        ('department_structure', '0004_auto_20220713_1218'),
        ('personnel', '0006_remove_staff_karaul'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineNoteTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_line_note', models.DateField(verbose_name='Дата')),
                ('gsm', models.IntegerField(blank=True, default=0, null=True, verbose_name='ГСМ')),
                ('foam', models.IntegerField(blank=True, default=0, null=True, verbose_name='Пена')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department_structure.firedepartment', verbose_name='Департамент')),
                ('trans_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.transstatus', verbose_name='Примечание техники')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transport', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Строевая записка',
                'verbose_name_plural': 'Строевые записки по техникам',
            },
        ),
        migrations.CreateModel(
            name='LineNoteMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_line_note', models.DateField(verbose_name='Дата')),
                ('gdzs', models.BooleanField(default=True, verbose_name='ГДЗС')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department_structure.firedepartment', verbose_name='Департамент')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.position', verbose_name='Должность')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.staff', verbose_name='ФИО')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.status', verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Строевая записка',
                'verbose_name_plural': 'Строевые записки личного состава',
            },
        ),
    ]
