# Generated by Django 4.0.4 on 2022-05-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_structure', '0001_initial'),
        ('personnel', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineNoteTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_line_note', models.DateField(verbose_name='Дата')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department_structure.firedepartment', verbose_name='Департамент')),
                ('trans_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.transstatus', verbose_name='Примечание техники')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transport', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Строевая записка',
                'verbose_name_plural': 'Строевые записки по техникам',
            },
        ),
        migrations.CreateModel(
            name='LineNoteMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_line_note', models.DateField(verbose_name='Дата')),
                ('gdzs', models.BooleanField(default=True, verbose_name='ГДЗС')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department_structure.firedepartment', verbose_name='Департамент')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.position', verbose_name='Должность')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.staff', verbose_name='ФИО')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.status', verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Строевая записка',
                'verbose_name_plural': 'Строевые записки личного состава',
            },
        ),
    ]
