# Generated by Django 3.1.7 on 2023-02-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linenotetrans',
            name='foam',
            field=models.IntegerField(default=0, verbose_name='Пена'),
        ),
        migrations.AlterField(
            model_name='linenotetrans',
            name='gsm',
            field=models.IntegerField(default=0, verbose_name='ГСМ'),
        ),
    ]
