# Generated by Django 3.1.7 on 2023-02-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_note', '0002_auto_20230215_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linenotetrans',
            name='foam',
        ),
        migrations.RemoveField(
            model_name='linenotetrans',
            name='gsm',
        ),
    ]
