# Generated by Django 3.1.7 on 2023-02-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_note', '0003_auto_20230216_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linenotetrans',
            options={'verbose_name': 'Строевая записка rewawer ', 'verbose_name_plural': 'Строевые rewaewar записки по техникам'},
        ),
    ]
