# Generated by Django 3.1.7 on 2023-02-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_note', '0004_auto_20230217_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linenotetrans',
            options={'verbose_name': 'Строевая записка-техника ', 'verbose_name_plural': 'Строевые записки по техникам'},
        ),
    ]
