# Generated by Django 3.1.7 on 2023-02-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_note', '0005_auto_20230217_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='linenotetrans',
            name='foam',
            field=models.IntegerField(default=1, verbose_name='Пена'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='gsm',
            field=models.IntegerField(default=1, verbose_name='ГСМ'),
        ),
    ]
