# Generated by Django 3.1.7 on 2023-02-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_note', '0006_auto_20230217_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='linenotetrans',
            name='blizzard',
            field=models.IntegerField(default=1, verbose_name='Пурга'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='current',
            field=models.IntegerField(default=1, verbose_name='ТОК'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='fire_monitors_portable',
            field=models.IntegerField(default=1, verbose_name='Лафетные сволы переносные'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='fire_monitors_stationary',
            field=models.IntegerField(default=1, verbose_name='Лафетные сволы стационарные'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='flashlight',
            field=models.IntegerField(default=1, verbose_name='электрофонарь'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='foam_stock',
            field=models.IntegerField(default=1, verbose_name='Пена на складе'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='gps_600',
            field=models.IntegerField(default=1, verbose_name='ГПС - 600'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='hydra_costume',
            field=models.IntegerField(default=1, verbose_name='Гидрокостюм'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='l1',
            field=models.IntegerField(default=1, verbose_name='Л - 1'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='motor_pumps_in_combat',
            field=models.IntegerField(default=1, verbose_name='мотопомпы в боевом расчете'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='motor_pumps_on_repair',
            field=models.IntegerField(default=1, verbose_name='мотопомпы на ремонте'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='portable_radios',
            field=models.IntegerField(default=1, verbose_name='переносные радиостанции'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='rescue_ropes',
            field=models.IntegerField(default=1, verbose_name='спасательные веревки'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='sleeves_51',
            field=models.IntegerField(default=1, verbose_name='Рукава 51мм'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='sleeves_66',
            field=models.IntegerField(default=1, verbose_name='Рукава 66мм'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='sleeves_77',
            field=models.IntegerField(default=1, verbose_name='Рукава 77мм'),
        ),
        migrations.AddField(
            model_name='linenotetrans',
            name='spotlight',
            field=models.IntegerField(default=1, verbose_name='прожектор'),
        ),
    ]
