# Generated by Django 3.1.7 on 2023-03-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_note', '0008_auto_20230217_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_additional_information', models.DateField(verbose_name='Дата')),
                ('foam_stock', models.IntegerField(default=0, verbose_name='Пена на складе')),
                ('hydra_costume', models.IntegerField(default=0, verbose_name='Гидрокостюм')),
                ('motor_pumps_on_repair', models.IntegerField(default=0, verbose_name='мотопомпы на ремонте')),
                ('motor_pumps_in_combat', models.IntegerField(default=0, verbose_name='мотопомпы в боевом расчете')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Дополнительная информация по строевой записке',
            },
        ),
        migrations.RemoveField(
            model_name='linenotetrans',
            name='foam_stock',
        ),
        migrations.RemoveField(
            model_name='linenotetrans',
            name='hydra_costume',
        ),
        migrations.RemoveField(
            model_name='linenotetrans',
            name='motor_pumps_in_combat',
        ),
        migrations.RemoveField(
            model_name='linenotetrans',
            name='motor_pumps_on_repair',
        ),
    ]
