# Generated by Django 3.1.7 on 2023-03-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department_structure', '0004_auto_20220713_1218'),
        ('combat_note', '0009_auto_20230301_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticvalues',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='department_structure.firedepartment', verbose_name='Департамент'),
            preserve_default=False,
        ),
    ]
