# Generated by Django 3.1.7 on 2023-01-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireHydrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicription', models.CharField(max_length=100, verbose_name='Описание')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=15, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=15, verbose_name='Долгота')),
                ('working', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Гидрант',
                'verbose_name_plural': 'Гидранты города',
            },
        ),
    ]
