# Generated by Django 3.1.7 on 2023-01-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firehydrant',
            name='dicription',
        ),
        migrations.AddField(
            model_name='firehydrant',
            name='created_date',
            field=models.DateTimeField(default=None, verbose_name='Дата и время добавления марки'),
        ),
        migrations.AddField(
            model_name='firehydrant',
            name='raw_address',
            field=models.TextField(default=None, max_length=100, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='firehydrant',
            name='user_comments',
            field=models.TextField(default='Комментарии', max_length=100, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='firehydrant',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=None, max_digits=15, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='firehydrant',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=None, max_digits=15, verbose_name='Долгота'),
        ),
    ]
