# Generated by Django 3.1.7 on 2023-01-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0002_auto_20230131_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firehydrant',
            name='latitude',
            field=models.FloatField(default=None, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='firehydrant',
            name='longitude',
            field=models.FloatField(default=None, verbose_name='Долгота'),
        ),
    ]
