# Generated by Django 3.1.7 on 2023-01-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0004_firehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurePlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=None, verbose_name='Дата и время добавления марки')),
                ('user_comments', models.TextField(default='Комментарии', max_length=100, verbose_name='Комментарии')),
                ('latitude', models.FloatField(default=None, verbose_name='Широта')),
                ('longitude', models.FloatField(default=None, verbose_name='Долгота')),
                ('raw_address', models.TextField(default=None, max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'ОПБ',
                'verbose_name_plural': 'Объекты Повышеной Безопасности',
            },
        ),
        migrations.RenameModel(
            old_name='FireHydrant',
            new_name='Hydrants',
        ),
    ]
