# Generated by Django 3.1.7 on 2023-02-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0005_auto_20230131_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon_1_Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=None, verbose_name='Широта')),
                ('longitude', models.FloatField(default=None, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'крайняя кордината желтой области ДЧС-1',
                'verbose_name_plural': 'Область вызова ДЧС-1',
            },
        ),
    ]
