# Generated by Django 4.0.4 on 2022-05-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='TransStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, null=True, unique=True, verbose_name='Примечание техники')),
            ],
            options={
                'verbose_name': 'Примечание техники',
                'verbose_name_plural': 'Примечания техники',
            },
        ),
        migrations.CreateModel(
            name='TransType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bort_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Бортовой номер')),
                ('year_of_trans', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('year_of_exploitation', models.IntegerField(blank=True, null=True, verbose_name='Срок эксплуатации')),
                ('season_to', models.BooleanField(default=True, verbose_name='Сезонное ТО')),
                ('new_number', models.CharField(blank=True, max_length=9, null=True, verbose_name='Регистр. номер')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.brand', verbose_name='Марка')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department_structure.firedepartment', verbose_name='Департамент')),
                ('trans_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.model', verbose_name='Модель')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.transtype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорты',
            },
        ),
    ]
