# Generated by Django 3.1.7 on 2023-02-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20220711_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='blizzard_default',
            field=models.IntegerField(default=0, verbose_name='Пурга'),
        ),
        migrations.AddField(
            model_name='transport',
            name='current_default',
            field=models.IntegerField(default=0, verbose_name='ТОК'),
        ),
        migrations.AddField(
            model_name='transport',
            name='fire_monitors_portable_default',
            field=models.IntegerField(default=0, verbose_name='Лафетные сволы переносные'),
        ),
        migrations.AddField(
            model_name='transport',
            name='fire_monitors_stationary_default',
            field=models.IntegerField(default=0, verbose_name='Лафетные сволы стационарные'),
        ),
        migrations.AddField(
            model_name='transport',
            name='flashlight_default',
            field=models.IntegerField(default=0, verbose_name='электрофонарь'),
        ),
        migrations.AddField(
            model_name='transport',
            name='foam_default',
            field=models.IntegerField(default=0, verbose_name='Пена'),
        ),
        migrations.AddField(
            model_name='transport',
            name='foam_stock_default',
            field=models.IntegerField(default=0, verbose_name='Пена на складе'),
        ),
        migrations.AddField(
            model_name='transport',
            name='gps_600_default',
            field=models.IntegerField(default=0, verbose_name='ГПС - 600'),
        ),
        migrations.AddField(
            model_name='transport',
            name='gsm_default',
            field=models.IntegerField(default=0, verbose_name='ГСМ'),
        ),
        migrations.AddField(
            model_name='transport',
            name='hydra_costume_default',
            field=models.IntegerField(default=0, verbose_name='Гидрокостюм'),
        ),
        migrations.AddField(
            model_name='transport',
            name='l1_default',
            field=models.IntegerField(default=0, verbose_name='Л - 1'),
        ),
        migrations.AddField(
            model_name='transport',
            name='motor_pumps_in_combat_default',
            field=models.IntegerField(default=0, verbose_name='мотопомпы в боевом расчете'),
        ),
        migrations.AddField(
            model_name='transport',
            name='motor_pumps_on_repair_default',
            field=models.IntegerField(default=0, verbose_name='мотопомпы на ремонте'),
        ),
        migrations.AddField(
            model_name='transport',
            name='portable_radios_default',
            field=models.IntegerField(default=0, verbose_name='переносные радиостанции'),
        ),
        migrations.AddField(
            model_name='transport',
            name='rescue_ropes_default',
            field=models.IntegerField(default=0, verbose_name='спасательные веревки'),
        ),
        migrations.AddField(
            model_name='transport',
            name='sleeves_51_default',
            field=models.IntegerField(default=0, verbose_name='Рукава 51мм'),
        ),
        migrations.AddField(
            model_name='transport',
            name='sleeves_66_default',
            field=models.IntegerField(default=0, verbose_name='Рукава 66мм'),
        ),
        migrations.AddField(
            model_name='transport',
            name='sleeves_77_default',
            field=models.IntegerField(default=0, verbose_name='Рукава 77мм'),
        ),
        migrations.AddField(
            model_name='transport',
            name='spotlight_default',
            field=models.IntegerField(default=0, verbose_name='прожектор'),
        ),
    ]
