# Generated by Django 3.1.7 on 2023-03-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20230228_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foam_stock_default', models.IntegerField(default=0, verbose_name='Пена на складе')),
                ('hydra_costume_default', models.IntegerField(default=0, verbose_name='Гидрокостюм')),
                ('motor_pumps_on_repair_default', models.IntegerField(default=0, verbose_name='мотопомпы на ремонте')),
                ('motor_pumps_in_combat_default', models.IntegerField(default=0, verbose_name='мотопомпы в боевом расчете')),
            ],
        ),
        migrations.RemoveField(
            model_name='transport',
            name='foam_stock_default',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='hydra_costume_default',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='motor_pumps_in_combat_default',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='motor_pumps_on_repair_default',
        ),
    ]
