# Generated by Django 3.1.7 on 2023-03-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20230301_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticValues',
        ),
    ]
